### ISSUE TITLE
SRF_II function problem

### ISSUE THREAD

**Issue by Aoqige** [JulianBMunoz/Zeus21#19]
The definition of the SRF_II  function is conflict with  the parameter passing in the UVLF_binned function. I can't generate the UVLFs now.
![120691724724817_ pic](https://github.com/user-attachments/assets/019ac5f5-14d1-4ca7-a752-e17f178be742)
![120701724724823_ pic](https://github.com/user-attachments/assets/d5e0690a-9abb-4f11-a31c-e92aa63360af)

**Comment by JulianBMunoz** [comment]
Should be solve by @hcruz1998 in #20, thanks!
